title: 'R Programming: advanced statistics and complex systems'
description: > 
  Exercises in R of the course Advanced Statistics for Physics Analysis and projects related to the course Statistical Mechanics of Complex Systems. <br /> 
  A.Y. 2021/2022.
theme: jekyll-theme-minimal
